import { StyleSheet } from 'react-native';
import type { MobileThemeColors } from '../theme';

export const createStyles = (theme: MobileThemeColors) =>
  StyleSheet.create({
    safeArea: { flex: 1, backgroundColor: theme.pageBackground },
    container: { gap: 16, padding: 20, paddingBottom: 32, width: '100%' },
    headerRow: {
      alignItems: 'flex-start',
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 12,
      justifyContent: 'space-between',
      width: '100%',
    },
    headerCopy: { flex: 1, gap: 5, minWidth: 0 },
    eyebrow: { color: theme.textMuted, fontSize: 11, fontWeight: '600', letterSpacing: 1.4 },
    title: { color: theme.textPrimary, fontSize: 28, fontWeight: '700', letterSpacing: -0.4 },
    apiHint: {
      color: theme.textMuted,
      flexShrink: 1,
      fontSize: 12,
      lineHeight: 18,
      width: '100%',
    },
    shadowNotice: {
      backgroundColor: theme.surface2,
      borderColor: theme.border,
      borderRadius: 6,
      borderWidth: 1,
      color: theme.textSecondary,
      fontSize: 12,
      lineHeight: 18,
      paddingHorizontal: 10,
      paddingVertical: 8,
      width: '100%',
    },
    themeButton: {
      backgroundColor: theme.surface2,
      borderColor: theme.borderStrong,
      borderRadius: 7,
      borderWidth: 1,
      flexShrink: 0,
      paddingHorizontal: 10,
      paddingVertical: 8,
    },
    themeButtonText: { color: theme.textSecondary, fontSize: 12, fontWeight: '600' },
    pressed: { opacity: 0.72 },
    focusRing: {
      borderColor: theme.brand,
      borderWidth: 2,
      outlineColor: theme.brand,
      outlineOffset: 2,
      outlineStyle: 'solid',
      outlineWidth: 2,
    },
    statusBanner: {
      backgroundColor: theme.surface1,
      borderColor: theme.border,
      borderLeftWidth: 3,
      borderRadius: 8,
      borderWidth: 1,
      gap: 4,
      padding: 12,
    },
    statusTitle: { color: theme.textPrimary, fontSize: 15, fontWeight: '600' },
    statusDescription: { color: theme.textSecondary, fontSize: 13, lineHeight: 19 },
    modeTabs: {
      alignSelf: 'flex-start',
      backgroundColor: theme.surface2,
      borderColor: theme.border,
      borderRadius: 8,
      borderWidth: 1,
      flexDirection: 'row',
      gap: 4,
      padding: 4,
    },
    modeTab: { borderRadius: 6, paddingHorizontal: 14, paddingVertical: 8 },
    activeModeTab: { backgroundColor: theme.surface1 },
    tabs: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    tab: {
      backgroundColor: theme.surface1,
      borderColor: theme.border,
      borderRadius: 7,
      borderWidth: 1,
      paddingHorizontal: 15,
      paddingVertical: 9,
    },
    activeTab: { backgroundColor: theme.surfaceSelected, borderColor: theme.brand },
    tabText: { color: theme.textSecondary, fontSize: 13, fontWeight: '600' },
    activeTabText: { color: theme.brand, fontSize: 13, fontWeight: '700' },
    metricsRow: {
      backgroundColor: theme.border,
      borderColor: theme.border,
      borderRadius: 8,
      borderWidth: 1,
      flexDirection: 'row',
      gap: 1,
      overflow: 'hidden',
    },
    metric: { backgroundColor: theme.surface1, flex: 1, gap: 5, padding: 12 },
    metricLabel: { color: theme.textMuted, fontSize: 12 },
    metricValue: { color: theme.textPrimary, fontSize: 14, fontWeight: '600' },
    sectionTitle: { color: theme.textPrimary, fontSize: 18, fontWeight: '700', marginTop: 4 },
    card: {
      backgroundColor: theme.surface1,
      borderColor: theme.border,
      borderRadius: 8,
      borderWidth: 1,
      gap: 6,
      padding: 14,
    },
    cardHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
    symbol: { color: theme.textPrimary, fontSize: 16, fontWeight: '700' },
    cardText: { color: theme.textSecondary, fontSize: 13, lineHeight: 19 },
    mutedText: { color: theme.textMuted, fontSize: 12 },
    staleText: { color: theme.warning, fontSize: 12, fontWeight: '700' },
    emptyText: { color: theme.textMuted, fontSize: 14, lineHeight: 21, paddingVertical: 20 },
    refreshButton: {
      alignItems: 'center',
      backgroundColor: theme.brand,
      borderRadius: 7,
      minHeight: 40,
      paddingHorizontal: 14,
      paddingVertical: 11,
      width: '100%',
    },
    refreshText: { color: theme.brandContrast, fontWeight: '700' },
  });

export type MobileStyles = ReturnType<typeof createStyles>;
