ALTER TABLE "Strategy"
ADD COLUMN "description" TEXT,
ADD COLUMN "status" TEXT NOT NULL DEFAULT 'draft',
ADD COLUMN "schemaVersion" INTEGER NOT NULL DEFAULT 1;

ALTER TABLE "StrategyVersion"
ADD COLUMN "schemaVersion" INTEGER NOT NULL DEFAULT 1;

ALTER TABLE "BacktestJob"
ADD COLUMN "progress" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "startedAt" TIMESTAMP(3),
ADD COLUMN "finishedAt" TIMESTAMP(3),
ADD COLUMN "engineVersion" TEXT,
ADD COLUMN "resultChecksum" TEXT;
